服务器前置任务(ubuntu使用 Centos项目注释或删掉)

- name: Pre_Docker
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
      ignore_errors: yes
  
# 核心任务

- name: Docker
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - variables.yml

  roles:
    - { role: common, tags: "common" }
    - { role: cloud, tags: "cloud" }
    - { role: docker, tags: "docker" }
    - { role: end, tags: "end" }